import {StyleSheet} from 'react-native';
import {Matrics, typography} from '../../Config/AppStyling';

export const styles = StyleSheet.create({
  TypeMaincontainer: {
    borderWidth: 1,
    borderColor: '#B3B3B3',
    margin: Matrics.ms(15),
    bottom: Matrics.ms(20),
    marginBottom: Matrics.ms(45),
    paddingVertical: Matrics.ms(30),
    paddingBottom: Matrics.ms(8),
  },
  serviceTypeContainer: {
    flex: 0.1,
    maxHeight: Matrics.ms(30),
    justifyContent: 'center',
    paddingHorizontal: Matrics.ms(15),
    borderBottomColor: '#DEDEDE',
    borderBottomWidth: 1,
    borderColor: '#B3B3B3',
    bottom: Matrics.ms(20),
    marginBottom: -20,
  },
  serviceTypeText: {
    color: '#555555',
    fontFamily: typography.fontFamily.Montserrat.Medium,
    fontSize: typography.fontSizes.fs10,
    color:'black'
  },
  setConstructionNumberContainer: {
    bottom: Matrics.ms(65),
    height: Matrics.ms(40),
    width: '56.7%',
    borderRightWidth: 1,
    borderLeftWidth: 1,
    borderBottomWidth: 1,
    justifyContent: 'center',
    borderColor: '#B3B3B3',
    marginLeft: Matrics.ms(15),
  },
  container: {
    flex: 1,
  },
  typeServiceCont: {
    flex: 0.1,
    margin: Matrics.ms(15),
    borderBottomColor: '#DEDEDE',
    borderBottomWidth: 1,
  },
  label: {
    fontFamily: typography.fontFamily.Montserrat.Regular,
    fontSize: typography.fontSizes.fs13,
    color: '#555555',
  },
  containerNumber: {
    flex: 1,
    paddingHorizontal: Matrics.ms(39.1),
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderColor: '#B3B3B3',
    height: '105%',
    marginTop: Matrics.ms(-15),
  },
  dropdownContainer: {
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    marginTop: Matrics.ms(12),
    borderRadius: Matrics.ms(5),
    justifyContent: 'center',
    // marginLeft: Matrics.ms(20),
    alignSelf: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#091242',
    height: Matrics.ms(40),
    // bottom: 8,
    width: 100,
  },
  dropdownContainer2: {
    flex: 1,
    flexDirection: 'row',
    marginTop: Matrics.ms(15),
    justifyContent: 'center',
    marginHorizontal: Matrics.ms(10),
    borderBottomWidth: 1,
    borderBottomColor: '#091242',
  },
  dropdownText: {
    paddingTop: Matrics.ms(6),
    paddingLeft: Matrics.ms(15),
    bottom: Matrics.ms(8),
    fontFamily: typography.fontFamily.Montserrat.SemiBold,
    fontSize: typography.fontSizes.fs10,
  },
  dropdownContainer3: {
    flex: 1,
    flexDirection: 'row',
    marginTop: Matrics.ms(12),
    justifyContent: 'center',
    borderBottomWidth: 0.5,
    borderBottomColor: '#091242',
    marginLeft: Matrics.ms(20),
    marginRight: Matrics.ms(11),
    left: Matrics.ms(5),
    bottom: Matrics.ms(5),
    borderBottomColor: '#B3B3B3',
  },
  dropdownText2: {
    paddingTop: Matrics.ms(6),
    paddingLeft: Matrics.ms(15),
    bottom: Matrics.ms(2),
    left: -1,
    fontFamily: typography.fontFamily.Montserrat.SemiBold,
    fontSize: typography.fontSizes.fs11,
    color:'black'
  },
  dropdownIcon: {
    left: 40,
    height: Matrics.ms(10),
    width: Matrics.ms(10),
    top: Matrics.ms(0),
  },
  dropdownIcon2: {
    left: 40,
    height: Matrics.ms(10),
    width: Matrics.ms(10),
    top: Matrics.ms(6),
  },
  buttonStyle: {
    backgroundColor: '#FF5454',
    borderWidth: 0,
    color: 'white',
    height: Matrics.ms(49),
    width: Matrics.ms(160),
    alignItems: 'center',
    // alignSelf: 'center',
    borderRadius: 16,
    marginBottom: 20,
    marginLeft: 15,
    marginRight: 15,
  },
  buttonStyle2: {
    backgroundColor: '#00C182',
    borderWidth: 0,
    color: 'white',
    height: Matrics.ms(49),
    width: Matrics.ms(160),
    alignItems: 'center',
    // alignSelf: 'center',
    borderRadius: 16,
    marginBottom: 20,
    marginRight: 16,
  },
  buttonTextStyle: {
    color: 'white',
    paddingTop: Matrics.ms(16),
    fontFamily: typography.fontFamily.Montserrat.Bold,
    fontSize: typography.fontSizes.fs13,
    textAlign: 'center',
    flexDirection: 'column',
  },
  modalContainer: {
    flex: 1,
    // justifyContent: 'center',
    alignItems: 'center',
    marginTop: Platform.select({
      android: Matrics.ms(145),
      ios: Matrics.ms(191),
    }),
    shadowColor: '#0A1931',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 14,
    // marginRight:Matrics.ms(20)
  },
  modalContent: {
    backgroundColor: '#EBF0FA',
    width: '90%',
    borderRadius: 10,
    paddingVertical: 0,
    maxHeight: '46%',
    borderWidth: 0.3,
  },
  modalContainer1: {
    flex: 1,
    alignItems: 'flex-end',
    marginTop: '66%',
    shadowColor: '#0A1931',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 14,
    marginRight: Matrics.ms(15),
  },
  modalContent1: {
    backgroundColor: '#EBF0FA',
    width: '37%',
    borderRadius: 10,
    paddingVertical: 0,
    maxHeight: '55%',
    borderWidth: 0.3,
  },
  ContainerSizemodalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'flex-end',
    marginTop: '66%',
    shadowColor: '#0A1931',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 14,
    marginRight: Matrics.ms(15),
  },
  ContainerSizeModalContent: {
    backgroundColor: '#EBF0FA',
    width: '37%',
    borderRadius: 10,
    paddingVertical: 0,
    maxHeight: '55%',
    borderWidth: 0.3,
  },
  SetTypesmodalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'flex-end',
    shadowColor: '#0A1931',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 14,
    marginRight: Matrics.ms(15),
  },
  SetTypesModalContent: {
    backgroundColor: '#EBF0FA',
    width: '37%',
    borderRadius: 10,
    paddingVertical: 0,
    maxHeight: '55%',
    borderWidth: 0.3,
  },
  GoodTypeModalContainer: {
    flex: 1,
    // justifyContent: 'center',
    alignItems: 'flex-end',
    marginTop: Matrics.ms(245),
    shadowColor: '#0A1931',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 14,
    marginRight: Matrics.ms(20),
  },
  GoodTypemodalContent: {
    backgroundColor: '#EBF0FA',
    width: '40%',
    borderRadius: 10,
    paddingVertical: 0,
    maxHeight: '17%',
    borderWidth: 0.3,
  },
  dropdownItem: {
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderBottomWidth: 0.5,
    borderBottomColor: '#CCCCCC',
  },
  dropdownItemText: {
    fontSize: typography.fontSizes.fs14,
    color: '#555555',
  },
  input: {
    textAlign: 'center',
    fontFamily: typography.fontFamily.Montserrat.Regular,
    fontSize: typography.fontSizes.fs10,
    color:'black',
    paddingHorizontal:10
  },
  centeredView: {
    flex: 1,
    justifyContent:'flex-end',
    alignItems: 'flex-end',
   marginBottom: Platform.select({
    ios: '48%',
    android: '59%',
  }),
    shadowColor: '#0A1931',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 14,
    marginRight: Matrics.ms(20),
  },
  modalView: {
    backgroundColor: '#EBF0FA',
    width: '35%',
    borderRadius: 10,
    paddingVertical: 10,
    maxHeight: '20%',
    borderWidth: 0.3,
  },
  modalText: {
    backgroundColor: '#EBF0FA',
    paddingVertical: 10,
    // borderBottomWidth: 1,
    alignSelf: 'center',
  },
  textInput: {
    fontFamily: typography.fontFamily.Montserrat.Regular,
    fontSize: typography.fontSizes.fs10,
  },
  ImagemodalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButton: {
    position: 'absolute',
    top: 20,
    right: 20,
    zIndex: 1,
  },
  noteContainer: {
    marginTop: Matrics.ms(0),
    borderRightWidth: 1,
    borderColor: '#B3B3B3',
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    height: Matrics.ms(75),
    // marginHorizontal: 16,
  },
  noteText: {
    marginLeft: Matrics.ms(18),
    marginTop: Matrics.ms(10),
    fontFamily: typography.fontFamily.Montserrat.Medium,
    fontSize: typography.fontSizes.fs10,
    color:'#555555'
  },
  noteTexInput: {
    borderWidth: 1,
    marginHorizontal: Matrics.ms(18),
    height: Matrics.ms(35),
    paddingLeft: Matrics.ms(15),
    borderRadius: Matrics.ms(5),
    margin: Matrics.ms(5),
    fontFamily: typography.fontFamily.Montserrat.Medium,
    fontSize: typography.fontSizes.fs10,
    paddingTop: Matrics.ms(10),
  },
  workerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: Matrics.ms(-35),
  },
  workersText: {
    marginLeft: Matrics.ms(16),
    marginTop: Matrics.ms(0),
    fontFamily: typography.fontFamily.Montserrat.SemiBold,
    fontSize: typography.fontSizes.fs14,
    color:'#555555'
  },
  addText: {
    fontFamily: typography.fontFamily.Montserrat.SemiBold,
    fontSize: typography.fontSizes.fs14,
    marginTop: Matrics.ms(0),
    marginRight: Matrics.ms(16),
    color:'#555555'
  },
  uploadContainer: {
    // backgroundColor: 'green',
    flex: 1,
    marginHorizontal: Matrics.ms(16),
    justifyContent: 'center',
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#B0B0B0',
    borderStyle: 'dashed',
    marginVertical: Matrics.ms(30),
    height: Matrics.ms(86),
    borderRadius: Matrics.ms(5),
    // width:Matrics.ms(346)
  },
  uploadIcon: {
    alignSelf: 'center',
    height: Matrics.ms(30),
    width: Matrics.ms(32),
  },
  uploadFileText:{
    fontFamily: typography.fontFamily.Montserrat.Medium,
    fontSize: typography.fontSizes.fs10,
    color: '#B1B1B1',
    marginTop: Matrics.ms(5),
  },
  downArrowIcon:{
    marginTop: Matrics.ms(30),
    bottom: Matrics.ms(15),
    left: Matrics.ms(5),
    height: Matrics.ms(10),
    width: Matrics.ms(10),
  },
  attachmentText:{
    marginLeft: Matrics.ms(16),
    marginTop: Matrics.ms(20),
    fontFamily: typography.fontFamily.Montserrat.SemiBold,
    fontSize: typography.fontSizes.fs14,
    color:'#555555'
  },
  goodTypemodalContainer: {
    flex: 1,
    alignItems: 'flex-end',
    marginTop: '96%',
    shadowColor: '#0A1931',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 14,
    marginRight: Matrics.ms(15),
  },
  goodTypemodalContent: {
    backgroundColor: '#EBF0FA',
    width: '37%',
    borderRadius: 10,
    paddingVertical: 0,
    maxHeight: '55%',
    borderWidth: 0.3,
  },
  workTypemodalContainer: {
    flex: 1,
    alignItems: 'flex-end',
    marginTop: Platform.select({
      ios: '65%',
      android:'55%',
    }),
    shadowColor: '#0A1931',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 14,
    marginRight: Matrics.ms(15),
  },
  workTypemodalContent: {
    backgroundColor: '#EBF0FA',
    width: '36%',
    borderRadius: 10,
    paddingVertical: 0,
    maxHeight: '55%',
    borderWidth: 0.3,
  },
  modalStyle:{
    marginTop: '115%',
  },
  SetbaumodalStyle:{
    marginTop: '120%',
  },
  Id1modalContent:{
    backgroundColor: '#EBF0FA',
    width: '37%',
    borderRadius: 10,
    paddingVertical: 0,
    maxHeight: '65%',
    borderWidth: 0.3,
    color:'black'
  }
});
