export default {
  NEW_APP_LOGO: require('../Assets/Icons/EDALOGO.jpg'),
  LOGIN_LOGO: require('../Assets/Icons/loginlogo3x.png'),
  EMAIL: require('../Assets/Icons/emailfieldicon3x.png'),
  PASSWORD: require('../Assets/Icons/passwordfieldicon3x.png'),
  HEADER_LOGO: require('../Assets/Icons/Headerlogo.png'),
  USER: require('../Assets/Icons/Rectangle80563x.png'),
  SIDEMENU: require('../Assets/Icons/sidemenuicon3x.png'),
  Message: require('../Assets/Icons/messagesicon3x.png'),
  SPLASH_ICON: require('../Assets/Icons/splashlogo3x.png'),
  LOGOUT_ICON: require('../Assets/Icons/logouticon3x.png'),
  SEPRATOR: require('../Assets/Icons/seprator.png'),
  CHANGE_PASSWORD: require('../Assets/Icons/changepassword3x.png'),
  DASHBOARD: require('../Assets/Icons/dashboardicon3x.png'),
  DAILY_LIST: require('../Assets/Icons/dailylists3x.png'),
  ADVANCES: require('../Assets/Icons/advances3x.png'),
  MESSAGES_ICON: require('../Assets/Icons/messagesicon.png'),
  CALENDER_ICON: require('../Assets/Icons/calendar3x.png'),
  SUPERVISION: require('../Assets/Icons/supervisoricon3x.png'),
  //=======>>> NFC ICONS <<<========//
  NFC: require('../Assets/Icons/nfc3x.png'),
  //=======>>> DAILY ICONS <<<========//
  ADD: require('../Assets/Icons/add2x.png'),
  MENU: require('../Assets/Icons/menu.png'),
  DELETE: require('../Assets/Icons/delete.png'),
  EDIT: require('../Assets/Icons/edit.png'),
  LEFT: require('../Assets/Icons/left.png'),
  RIGHT: require('../Assets/Icons/rightarrow.png'),
  CANCELFILL: require('../Assets/Icons/cancelfil.png'),
  DOWNARROW: require('../Assets/Icons/downarrow.png'),
  BACKICON: require('../Assets/Icons/Back.png'),

  //===========CREATE DAILY LIST  ===========
  UPLOAD: require('../Assets/Icons/Upload.png'),
  PLUS: require('../Assets/Icons/plus.png'),
  MINUS: require('../Assets/Icons/Minus.png'),
  ADDCREATE: require('../Assets/Icons/ADDCRATE.png'),
  TIMER: require('../Assets/Icons/timer.png'),
  DELETEUP: require('../Assets/Icons/deleteUpload.png'),
  //===========CREATE DAILY LIST  ===========

  PDF: require('../Assets/Icons/pdf.png'),
  ARCHIVE: require('../Assets/Icons/archive.png'),
  CLOSE: require('../Assets/Icons/close.png'),
  EYE: require('../Assets/Icons/eye.png'),
  ARCHIVE_ICON: require('../Assets/Icons/box.png'),
  BACK_ICON: require('../Assets/Icons/famicons--chevron-back-outline.png'),
  UP_ARROW: require('../Assets/Icons/arrow-up.png'),
  TICK_ICON: require('../Assets/Icons/flowbite--check-outline.png'),
  FILTER: require('../Assets/Icons/filter.png'),
  CROSS: require('../Assets/Icons/cross.png'),
  SEARCH: require('../Assets/Icons/search.png'),
  MOVE_TO_ARCHIVE: require('../Assets/Icons/move-to-archive.png'),
  MARK_AS_READ: require('../Assets/Icons/mark-as-read.png'),
  RESTORE: require('../Assets/Icons/restore.png'),
  THREE_DOTS: require('../Assets/Icons/three-dots.png'),
  SELECT_ALL: require('../Assets/Icons/select-all.png'),
  /* ------------------------------ Country Flags ----------------------------- */
  RUS: require('../Assets/Flags/russian.png'),
  UK: require('../Assets/Flags/english.png'),
  GER: require('../Assets/Flags/german.png'),
  POL: require('../Assets/Flags/polish.png'),
  UKA: require('../Assets/Flags/ukranian.png'),
  ZH: require('../Assets/Flags/chinese.png'),
  /* ---------------------------- Password helpers ---------------------------- */
  EYE_OPEN: require('../Assets/Icons/eye-new.png'),
  EYE_CLOSE: require('../Assets/Icons/eye-off.png'),

  // Notification
  NOTIFICATION_ICON: require('../Assets/Icons/basil--notification-outline.png'),
  USER_PROFILE: require('../Assets/Icons/user-profile.png'),
  HOURLY_LIST: require('../Assets/Icons/hourly-list.png'),
  SICK_LEAVES: require('../Assets/Icons/sick-leaves.png'),
  VACATIONS: require('../Assets/Icons/vacations.png'),
};
